[package]
name = "simd"
version = "0.1.0"
authors = ["David Karlsson <dkarlss@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
